github:
  repositoryFullName: dllatas/helm-charts

httpRoute:
  enabled: true
  parentRefs:
    - namespace: ingress
      name: gateway
  hostnames:
    - build.harokilabs.com
  pathPrefix: /charts/
