apiVersion: gateway.networking.k8s.io/v1alpha2
tcpRoutes:
  - name: example-tcp-route
    namespace: default
    spec:
      parentRefs:
        - namespace: staging
          name: tunnel
      rules:
        - backendRefs:
            - name: tunnel
              port: 7000
