apiVersion: telemetry.istio.io/v1

telemetries:
  - name: mesh-config
    namespace: istio-system
    labels: {}
    annotations: {}
    spec:
      accessLogging:
        - providers:
            - name: envoy
      tracing:
        - providers:
            - name: otel-tracing
          randomSamplingPercentage: 100
