externalSecrets:
  - name: minio-creds
    namespace: storage
    refreshInterval: 30m
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      name: minio-creds
    dataFrom:
      - extract:
          key: kv/netcup/minio
