apiVersion: external-secrets.io/v1

defaults:
  namespace: staging
  refreshInterval: 1m
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

externalSecrets:
  - name: example-a
    target:
      name: example-a
    data:
      - secretKey: value
        remoteRef:
          key: secret/example-a
  - name: example-b
    annotations:
      example.com/source: custom
    target:
      name: example-b
    dataFrom:
      - extract:
          key: secret/example-b
