nameOverride: ""
fullnameOverride: ""

apiVersions:
  tekton: tekton.dev/v1beta1
  triggers: triggers.tekton.dev/v1beta1
  gateway: gateway.networking.k8s.io/v1

pipeline:
  name: helm-charts-ci
  serviceAccountName: ci-services
  toolsImage: quay.io/helmpack/chart-testing:v3.14.0
  cloneTaskRef: git-clone

publish:
  enabled: true
  targetBranch: master
  secretName: helm-charts-publish
  secretKeys:
    harborRepo: harbor_oci_repo
    harborUsername: harbor_username
    harborPassword: harbor_password

run:
  pvcSize: 2Gi
  pvcAccessModes:
    - ReadWriteOnce
  fsGroup: 65532
  skipE2E: true
  sshSecretName: ssh-key
  dockerSecretName: docker-credentials

triggerBinding:
  name: helm-charts-webhook

triggerTemplate:
  name: helm-charts-ci

eventListener:
  name: github-helm-charts
  serviceAccountName: ci-services

github:
  secretName: github-secret
  secretKey: secretToken
  eventTypes:
    - push
    - pull_request
  repositoryFullName: dllatas/helm-charts
  extraFilter: ""

httpRoute:
  enabled: true
  name: tekton-github-helm-charts
  parentRefs:
    - namespace: ingress
      name: gateway
  hostnames:
    - build.harokilabs.com
  pathPrefix: /charts/
