apiVersion: external-secrets.io/v1beta1

defaults:
  refreshInterval: 1h
  labels: {}
  annotations: {}
  secretStoreRef: {}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

externalSecrets:
  - name: example
    namespace: default
    refreshInterval: 1h
    labels: {}
    annotations: {}
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      name: example
      creationPolicy: Owner
      deletionPolicy: Retain
    data:
      - secretKey: value
        remoteRef:
          key: kv/example
