{{- range $serviceAccount := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name }}
  namespace: {{ $serviceAccount.namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/name: {{ $.Chart.Name | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
{{- with $serviceAccount.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with $serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if hasKey $serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- with $serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
