{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "redis.labels" (dict "root" . "component" "auth") | indent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretPasswordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
