defaults:
  labels: {}
  annotations: {}
  automountServiceAccountToken: true
  imagePullSecrets: []
  secrets: []

serviceAccounts:
  - name: example
    namespace: default
    labels: {}
    annotations: {}
    automountServiceAccountToken: true
    imagePullSecrets: []
    secrets: []
