{{- if .Values.triggerBinding.create }}
apiVersion: {{ .Values.apiVersions.triggers }}
kind: TriggerBinding
metadata:
  name: {{ include "tekton-ci.triggerBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tekton-ci.commonLabels" . | nindent 4 }}
spec:
  params:
    {{- if .Values.triggerBinding.params }}
    {{- toYaml .Values.triggerBinding.params | nindent 4 }}
    {{- else }}
    - name: git-repo-url
      value: "$(body.repository.ssh_url)"
    - name: git-revision
      value: "$(extensions.git_revision)"
    - name: branch-name
      value: "$(extensions.branch_name)"
    - name: branch-slug
      value: "$(extensions.branch_slug)"
    - name: event-type
      value: "$(header.X-GitHub-Event)"
    - name: before-sha
      value: "$(extensions.before_sha)"
    - name: after-sha
      value: "$(extensions.after_sha)"
    {{- if eq .Values.pipeline.mode "imageBuild" }}
    - name: git-revision-short
      value: "$(extensions.short_sha)"
    {{- end }}
    {{- end }}
{{- end }}
