apiVersion: batch/v1

global: {}

jobs:
  - name: example-job
    namespace: default
    isEnabled: true
    labels: {}
    annotations: {}
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: example
              image: busybox:1.36.1
              command: ["sh", "-c", "echo hello"]
