apiVersion: external-secrets.io/v1

clusterSecretStores:
  - name: example-store
    labels: {}
    annotations: {}
    spec:
      provider:
        vault:
          server: http://vault.vault.svc.cluster.local:8200
          path: secret
          version: v2
          auth:
            kubernetes:
              mountPath: kubernetes
              role: reader
              serviceAccountRef:
                namespace: vault
                name: eso
